lesscss=r'''
var _less,location={hostname:"0.0.0.0",protocol:"",port:[],href:"/"},document={getElementsByTagName:function(){return[]}},window={document:document,location:location,localStorage:{},XMLHttpRequest:function(){},less:{env:"development",async:!1,fileAsync:!1,poll:1E3,functions:{},dumpLineNumbers:"comments",relativeUrls:!1,rootpath:":/a.com/"}};
(function(u,S){function q(c){return u.less[c.split("/")[1]]}function O(){"development"===h.env?(h.optimization=0,h.watchTimer=setInterval(function(){h.watchMode&&K(function(c,b,g,e,f){b&&E(b.toCSS(),e,f.lastModified)})},h.poll)):h.optimization=3}function L(){for(var c=document.getElementsByTagName("style"),b=0;b<c.length;b++)c[b].type.match(M)&&(new h.Parser({filename:document.location.href.replace(/#.*$/,""),dumpLineNumbers:h.dumpLineNumbers})).parse(c[b].innerHTML||"",function(g,e){var f=e.toCSS(),
d=c[b];d.type="text/css";d.styleSheet?d.styleSheet.cssText=f:d.innerHTML=f})}function K(c,b){for(var g=0;g<h.sheets.length;g++)N(h.sheets[g],c,b,h.sheets.length-(g+1))}function P(c,b){var g=F(c),e=F(b),f,d,p="";if(g.hostPart!==e.hostPart)return"";d=Math.max(e.directories.length,g.directories.length);for(f=0;f<d&&e.directories[f]===g.directories[f];f++);e=e.directories.slice(f);g=g.directories.slice(f);for(f=0;f<e.length-1;f++)p+="../";for(f=0;f<g.length-1;f++)p+=g[f]+"/";return p}function F(c,b){var g=
/^((?:[a-z-]+:)?\/\/(?:[^\/\?#]*\/)|([\/\\]))?((?:[^\/\\\?#]*[\/\\])*)([^\/\\\?#]*)([#\?].*)?$/,e=c.match(g),f={},d=[];if(!e)throw Error("Could not parse sheet href - '"+c+"'");if(!e[1]||e[2]){g=b.match(g);if(!g)throw Error("Could not parse page url - '"+b+"'");e[1]=g[1];e[2]||(e[3]=g[3]+e[3])}if(e[3]){d=e[3].replace("\\","/").split("/");for(g=0;g<d.length;g++)".."===d[g]&&0<g&&(d.splice(g-1,2),g-=2)}f.hostPart=e[1];f.directories=d;f.path=e[1]+d.join("/");f.fileUrl=f.path+(e[4]||"");f.url=f.fileUrl+
(e[5]||"");return f}function N(c,b,g,e){var f=c.contents||{},d=c.files||{},p=F(c.href,u.location.href),n=p.url,k=t&&t.getItem(n),s=t&&t.getItem(n+":timestamp"),l={css:k,timestamp:s},B;B=h.relativeUrls?h.rootpath?c.entryPath?F(h.rootpath+P(p.path,c.entryPath)).path:h.rootpath:p.path:h.rootpath?h.rootpath:c.entryPath?c.entryPath:p.path;Q(n,c.type,function(k,m){H+=k.replace(/@import .+?;/ig,"");if(!g&&l&&m&&(new Date(m)).valueOf()===(new Date(l.timestamp)).valueOf())E(l.css,c),b(null,null,k,c,{local:!0,
remaining:e},n);else try{f[n]=k,(new h.Parser({optimization:h.optimization,paths:[p.path],entryPath:c.entryPath||p.path,mime:c.type,filename:n,rootpath:B,relativeUrls:c.relativeUrls,contents:f,files:d,dumpLineNumbers:h.dumpLineNumbers})).parse(k,function(d,f){if(d)return I(d,n);try{b(d,f,k,c,{local:!1,lastModified:m,remaining:e},n);var g=document.getElementById("less-error-message:"+J(n));g&&g.parentNode.removeChild(g)}catch(p){I(p,n)}})}catch(s){I(s,n)}},function(d,b){throw Error("Couldn't load "+
b+" ("+d+")");})}function J(c){return c.replace(/^[a-z]+:\/\/?[^\/]+/,"").replace(/^\//,"").replace(/\.[a-zA-Z]+$/,"").replace(/[^\.\w-]+/g,"-").replace(/\./g,":")}function E(c,b,g){var e,f=b.href||"",d="less:"+(b.title||J(f));if(null===(e=document.getElementById(d)))e=document.createElement("style"),e.type="text/css",b.media&&(e.media=b.media),e.id=d,b=b&&b.nextSibling||null,(b||document.getElementsByTagName("head")[0]).parentNode.insertBefore(e,b);if(e.styleSheet)try{e.styleSheet.cssText=c}catch(p){throw Error("Couldn't reassign styleSheet.cssText.");
}else b=document.createTextNode(c),0<e.childNodes.length?e.firstChild.nodeValue!==b.nodeValue&&e.replaceChild(b,e.firstChild):e.appendChild(b);if(g&&t){w("saving "+f+" to cache.");try{t.setItem(f,c),t.setItem(f+":timestamp",g)}catch(n){w("failed to save")}}}function Q(c,b,g,e){function f(d,b,f){200<=d.status&&300>d.status?b(d.responseText,d.getResponseHeader("Last-Modified")):"function"===typeof f&&f(d.status,c)}var d=R(),p=G?h.fileAsync:h.async;"function"===typeof d.overrideMimeType&&d.overrideMimeType("text/css");
d.open("GET",c,p);d.setRequestHeader("Accept",b||"text/x-less, text/css; q=0.9, */*; q=0.5");d.send(null);G&&!h.fileAsync?0===d.status||200<=d.status&&300>d.status?g(d.responseText):e(d.status,c):p?d.onreadystatechange=function(){4==d.readyState&&f(d,g,e)}:f(d,g,e)}function R(){if(u.XMLHttpRequest)return new XMLHttpRequest;try{return new ActiveXObject("MSXML2.XMLHTTP.3.0")}catch(c){return w("browser doesn't support AJAX."),null}}function w(c){"development"==h.env&&"undefined"!==typeof console&&console.log("less: "+
c)}function I(c,b){var g="less-error-message:"+J(b),e=document.createElement("div"),f,d,p=[];d=c.filename||b;var n=d.match(/([^\/]+(\?.*)?)$/)[1];e.id=g;e.className="less-error-message";d="<h3>"+(c.message||"There is an error in your .less file")+'</h3><p>in <a href="'+d+'">'+n+"</a> ";n=function(d,b,f){d.extract[b]&&p.push('<li><label>{line}</label><pre class="{class}">{content}</pre></li>'.replace(/\{line\}/,parseInt(d.line)+(b-1)).replace(/\{class\}/,f).replace(/\{content\}/,d.extract[b]))};c.stack?
d+="<br/>"+c.stack.split("\n").slice(1).join("<br/>"):c.extract&&(n(c,0,""),n(c,1,"line"),n(c,2,""),d+="on line "+c.line+", column "+(c.column+1)+":</p><ul>"+p.join("")+"</ul>");e.innerHTML=d;E(".less-error-message ul, .less-error-message li {\nlist-style-type: none;\nmargin-right: 15px;\npadding: 4px 0;\nmargin: 0;\n}\n.less-error-message label {\nfont-size: 12px;\nmargin-right: 15px;\npadding: 4px 0;\ncolor: #cc7777;\n}\n.less-error-message pre {\ncolor: #dd6666;\npadding: 4px 0;\nmargin: 0;\ndisplay: inline-block;\n}\n.less-error-message pre.line {\ncolor: #ff0000;\n}\n.less-error-message h3 {\nfont-size: 20px;\nfont-weight: bold;\npadding: 15px 0 5px 0;\nmargin: 0;\n}\n.less-error-message a {\ncolor: #10a\n}\n.less-error-message .error {\ncolor: red;\nfont-weight: bold;\npadding-bottom: 2px;\nborder-bottom: 1px dashed red;\n}",
{title:"error-message"});e.style.cssText="font-family: Arial, sans-serif;border: 1px solid #e00;background-color: #eee;border-radius: 5px;-webkit-border-radius: 5px;-moz-border-radius: 5px;color: #e00;padding: 15px;margin-bottom: 15px";"development"==h.env&&(f=setInterval(function(){document.body&&(document.getElementById(g)?document.body.replaceChild(e,document.getElementById(g)):document.body.insertBefore(e,document.body.firstChild),clearInterval(f))},10))}Array.isArray||(Array.isArray=function(c){return"[object Array]"===
Object.prototype.toString.call(c)||c instanceof Array});Array.prototype.forEach||(Array.prototype.forEach=function(c,b){for(var g=this.length>>>0,e=0;e<g;e++)e in this&&c.call(b,this[e],e,this)});Array.prototype.map||(Array.prototype.map=function(c,b){for(var g=this.length>>>0,e=Array(g),f=0;f<g;f++)f in this&&(e[f]=c.call(b,this[f],f,this));return e});Array.prototype.filter||(Array.prototype.filter=function(c,b){for(var g=[],e=0;e<this.length;e++)c.call(b,this[e])&&g.push(this[e]);return g});Array.prototype.reduce||
(Array.prototype.reduce=function(c){var b=this.length>>>0,g=0;if(0===b&&1===arguments.length)throw new TypeError;if(2<=arguments.length)var e=arguments[1];else{do{if(g in this){e=this[g++];break}if(++g>=b)throw new TypeError;}while(1)}for(;g<b;g++)g in this&&(e=c.call(null,e,this[g],g,this));return e});Array.prototype.indexOf||(Array.prototype.indexOf=function(c,b){var g=this.length,e=b||0;if(!g||e>=g)return-1;for(0>e&&(e+=g);e<g;e++)if(Object.prototype.hasOwnProperty.call(this,e)&&c===this[e])return e;
return-1});Object.keys||(Object.keys=function(c){var b=[],g;for(g in c)Object.prototype.hasOwnProperty.call(c,g)&&b.push(g);return b});String.prototype.trim||(String.prototype.trim=function(){return String(this).replace(/^\s\s*/,"").replace(/\s\s*$/,"")});var h,l;h={env:"development",async:!1,fileAsync:!1,poll:1E3,functions:{},dumpLineNumbers:"all",relativeUrls:!1,rootpath:":/a.com/"};"object"===typeof environment&&"[object Environment]"==={}.toString.call(environment)?(h="undefined"===typeof u?{}:
u.less={},l=h.tree={},h.mode="rhino"):"undefined"===typeof u?(h=exports,l=q("./tree"),h.mode="node"):("undefined"===typeof u.less&&(u.less={}),h=u.less,l=u.less.tree={},h.mode="browser");h.Parser=function(c){function b(){u=x[v];w=A=m}function g(){x[v]=u;w=m=A}function e(){m>w&&(x[v]=x[v].slice(m-w),w=m)}function f(d){d=d.charCodeAt(0);return 32===d||10===d||9===d}function d(d){var b;if(d instanceof Function)return d.call(C.parsers);if("string"===typeof d)d=r.charAt(m)===d?d:null,b=1,e();else if(e(),
d=d.exec(x[v]))b=d[0].length;else return null;if(d){for(var c=m+x[v].length,g=m+=b;m<c&&f(r.charAt(m));)m++;x[v]=x[v].slice(b+(m-g));w=m;0===x[v].length&&v<x.length-1&&v++;return"string"===typeof d?d:1===d.length?d[0]:d}}function p(b,f){var c=d(b);if(c)return c;n(f||("string"===typeof b?"expected '"+b+"' got '"+r.charAt(m)+"'":"unexpected token"))}function n(d,b){var f=Error(d);f.index=m;f.type=b||"Syntax";throw f;}function k(d){return"string"===typeof d?r.charAt(m)===d:d.test(x[v])?!0:!1}function s(d,
b){for(var f=d,c=-1;0<=f&&"\n"!==b.charAt(f);f--)c++;return{line:"number"===typeof d?(b.slice(0,d).match(/\n/g)||"").length:null,column:c}}function y(d,b,f){d=s(d,b).line+1;f="browser"===h.mode||"rhino"===h.mode?f.filename:q("path").resolve(f.filename);return{lineNumber:d,fileName:f}}function B(d,b){var f;f=d.filename&&b.filename&&d.filename!==b.filename?C.imports.contents[d.filename]:r;var c=s(d.index,f),g=c.line,c=c.column,e=f.split("\n");this.type=d.type||"Syntax";this.message=d.message;this.filename=
d.filename||b.filename;this.index=d.index;this.line="number"===typeof g?g+1:null;this.callLine=d.call&&s(d.call,f).line+1;this.callExtract=e[s(d.call,f).line];this.stack=d.stack;this.column=c;this.extract=[e[g-1],e[g],e[g+1]]}var r,m,v,u,A,t,x,w,C;c=c||{};c.contents||(c.contents={});c.rootpath=c.rootpath||"";c.files||(c.files={});var E=function(){},F=this.imports={paths:c.paths||[],queue:[],files:c.files,contents:c.contents,mime:c.mime,error:null,push:function(d,b){var f=this;this.queue.push(d);h.Parser.importer(d,
this.paths,function(c,g,e){f.queue.splice(f.queue.indexOf(d),1);var p=e in f.files;f.files[e]=g;c&&!f.error&&(f.error=c);b(c,g,p);0===f.queue.length&&E(f.error)},c)}};this.env=c=c||{};this.optimization="optimization"in this.env?this.env.optimization:1;this.env.filename=this.env.filename||null;return C={imports:F,parse:function(b,f){var g,e,p,n=null;m=v=w=t=0;r=b.replace(/\r\n/g,"\n");r=r.replace(/^\uFEFF/,"");x=function(d){for(var b=0,f=/(?:@\{[\w-]+\}|[^"'`\{\}\/\(\)\\])+/g,g=/\/\*(?:[^*]|\*+[^\/*])*\*+\/|\/\/.*/g,
e=/"((?:[^"\\\r\n]|\\.)*)"|'((?:[^'\\\r\n]|\\.)*)'|`((?:[^`]|\\.)*)`/g,p=0,z,D=d[0],k,m=0,s,h;m<r.length;){f.lastIndex=m;if((z=f.exec(r))&&z.index===m)m+=z[0].length,D.push(z[0]);s=r.charAt(m);g.lastIndex=e.lastIndex=m;if((z=e.exec(r))&&z.index===m)m+=z[0].length,D.push(z[0]);else{if(!k&&"/"===s&&(h=r.charAt(m+1),"/"===h||"*"===h))if((z=g.exec(r))&&z.index===m){m+=z[0].length;D.push(z[0]);continue}switch(s){case "{":if(!k){p++;D.push(s);break}case "}":if(!k){p--;D.push(s);d[++b]=D=[];break}case "(":if(!k){k=
!0;D.push(s);break}case ")":if(k){k=!1;D.push(s);break}default:D.push(s)}m++}}0!=p&&(n=new B({index:m-1,type:"Parse",message:0<p?"missing closing `}`":"missing opening `{`",filename:c.filename},c));return d.map(function(d){return d.join("")})}([[]]);if(n)return f(n,c);try{g=new l.Ruleset([],d(this.parsers.primary)),g.root=!0}catch(k){return f(new B(k,c))}g.toCSS=function(d){return function(b,f){var g=[];b=b||{};"object"===typeof f&&!Array.isArray(f)&&(f=Object.keys(f).map(function(d){var b=f[d];b instanceof
l.Value||(b instanceof l.Expression||(b=new l.Expression([b])),b=new l.Value([b]));return new l.Rule("@"+d,b,!1,0)}),g=[new l.Ruleset(null,f)]);try{var e=d.call(this,{frames:g}).toCSS([],{compress:b.compress||!1,dumpLineNumbers:c.dumpLineNumbers})}catch(z){throw new B(z,c);}if(g=C.imports.error){if(g instanceof B)throw g;throw new B(g,c);}return b.yuicompress&&"node"===h.mode?q("ycssmin").cssmin(e):b.compress?e.replace(/(\s)+/g,"$1"):e}}(g.eval);if(m<r.length-1){m=t;p=r.split("\n");e=(r.slice(0,m).match(/\n/g)||
"").length+1;for(var s=m,y=-1;0<=s&&"\n"!==r.charAt(s);s--)y++;n={type:"Parse",message:"Syntax Error on line "+e,index:m,filename:c.filename,line:e,column:y,extract:[p[e-2],p[e-1],p[e]]}}0<this.imports.queue.length?E=function(d){(d=n||d)?f(d):f(null,g)}:f(n,g)},parsers:{primary:function(){for(var b,f=[];(b=d(this.mixin.definition)||d(this.rule)||d(this.ruleset)||d(this.mixin.call)||d(this.comment)||d(this.directive))||d(/^[\s\n]+/)||d(/^;+/);)b&&f.push(b);return f},comment:function(){var b;if("/"===
r.charAt(m)){if("/"===r.charAt(m+1))return new l.Comment(d(/^\/\/.*/),!0);if(b=d(/^\/\*(?:[^*]|\*+[^\/*])*\*+\/\n?/))return new l.Comment(b)}},entities:{quoted:function(){var b;b=m;var f;"~"===r.charAt(b)&&(b++,f=!0);if(!('"'!==r.charAt(b)&&"'"!==r.charAt(b))&&(f&&d("~"),b=d(/^"((?:[^"\\\r\n]|\\.)*)"|'((?:[^'\\\r\n]|\\.)*)'/)))return new l.Quoted(b[0],b[1]||b[2],f)},keyword:function(){var b;if(b=d(/^[_A-Za-z-][_A-Za-z0-9-]*/))return l.colors.hasOwnProperty(b)?new l.Color(l.colors[b].slice(1)):new l.Keyword(b)},
call:function(){var b,f,g=m;if(b=/^([\w-]+|%|progid:[\w\.]+)\(/.exec(x[v])){b=b[1];f=b.toLowerCase();if("url"===f)return null;m+=b.length;if("alpha"===f&&(f=d(this.alpha),"undefined"!==typeof f))return f;d("(");f=d(this.entities.arguments);if(d(")")&&b)return new l.Call(b,f,g,c.filename)}},arguments:function(){for(var b=[],f;(f=d(this.entities.assignment)||d(this.expression))&&!(b.push(f),!d(",")););return b},literal:function(){return d(this.entities.ratio)||d(this.entities.dimension)||d(this.entities.color)||
d(this.entities.quoted)||d(this.entities.unicodeDescriptor)},assignment:function(){var b,f;if((b=d(/^\w+(?=\s?=)/i))&&d("=")&&(f=d(this.entity)))return new l.Assignment(b,f)},url:function(){var b;if("u"===r.charAt(m)&&d(/^url\(/))return b=d(this.entities.quoted)||d(this.entities.variable)||d(/^(?:(?:\\[\(\)'"])|[^\(\)'"])+/)||"",p(")"),new l.URL(null!=b.value||b instanceof l.Variable?b:new l.Anonymous(b),c.rootpath)},variable:function(){var b,f=m;if("@"===r.charAt(m)&&(b=d(/^@@?[\w-]+/)))return new l.Variable(b,
f,c.filename)},variableCurly:function(){var b,f=m;if("@"===r.charAt(m)&&(b=d(/^@\{([\w-]+)\}/)))return new l.Variable("@"+b[1],f,c.filename)},color:function(){var b;if("#"===r.charAt(m)&&(b=d(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})/)))return new l.Color(b[1])},dimension:function(){var b;b=r.charCodeAt(m);if(!(57<b||43>b)&&!(47===b||44==b))if(b=d(/^([+-]?\d*\.?\d+)(px|%|em|pc|ex|in|deg|s|ms|pt|cm|mm|rad|grad|turn|dpi|dpcm|dppx|rem|vw|vh|vmin|vm|ch)?/))return new l.Dimension(b[1],b[2])},ratio:function(){var b;
b=r.charCodeAt(m);if(!(57<b||48>b))if(b=d(/^(\d+\/\d+)/))return new l.Ratio(b[1])},unicodeDescriptor:function(){var b;if(b=d(/^U\+[0-9a-fA-F?]+(\-[0-9a-fA-F?]+)?/))return new l.UnicodeDescriptor(b[0])},javascript:function(){var b;b=m;var f;"~"===r.charAt(b)&&(b++,f=!0);if("`"===r.charAt(b)&&(f&&d("~"),b=d(/^`([^`]*)`/)))return new l.JavaScript(b[1],m,f)}},variable:function(){var b;if("@"===r.charAt(m)&&(b=d(/^(@[\w-]+)\s*:/)))return b[1]},shorthand:function(){var f,c;if(k(/^[@\w.%-]+\/[@\w.-]+/)){b();
if((f=d(this.entity))&&d("/")&&(c=d(this.entity)))return new l.Shorthand(f,c);g()}},mixin:{call:function(){var f=[],e,s,h=[],B=[],y,q,v,u=m;e=r.charAt(m);var w,t,x=!1;if(!("."!==e&&"#"!==e)){for(b();e=d(/^[#.](?:[\w-]|\\(?:[A-Fa-f0-9]{1,6} ?|[^A-Fa-f0-9]))+/);)f.push(new l.Element(s,e,m)),s=d(">");if(d("(")){for(e=[];y=d(this.expression);)if(s=null,t=y,1==y.value.length&&(y=y.value[0],y instanceof l.Variable&&d(":")&&(0<e.length&&(q&&n("Cannot mix ; and , as delimiter types"),v=!0),t=p(this.expression),
s=w=y.name)),e.push(t),B.push({name:s,value:t}),!d(",")&&(d(";")||q))v&&n("Cannot mix ; and , as delimiter types"),q=!0,1<e.length&&(t=new l.Value(e)),h.push({name:w,value:t}),w=null,e=[],v=!1;p(")")}h=q?h:B;d(this.important)&&(x=!0);if(0<f.length&&(d(";")||k("}")))return new l.mixin.Call(f,h,u,c.filename,x);g()}},definition:function(){var f,c=[],e,n,s,h=!1;if(!("."!==r.charAt(m)&&"#"!==r.charAt(m)||k(/^[^{]*\}/)))if(b(),f=d(/^([#.](?:[\w-]|\\(?:[A-Fa-f0-9]{1,6} ?|[^A-Fa-f0-9]))+)\s*\(/)){f=f[1];
do if(d(this.comment),"."===r.charAt(m)&&d(/^\.{3}/)){h=!0;c.push({variadic:!0});break}else if(e=d(this.entities.variable)||d(this.entities.literal)||d(this.entities.keyword))if(e instanceof l.Variable)if(d(":"))n=p(this.expression,"expected expression"),c.push({name:e.name,value:n});else if(d(/^\.{3}/)){c.push({name:e.name,variadic:!0});h=!0;break}else c.push({name:e.name});else c.push({value:e});else break;while(d(",")||d(";"));d(")")||(t=m,g());d(this.comment);d(/^when/)&&(s=p(this.conditions,
"expected condition"));if(e=d(this.block))return new l.mixin.Definition(f,c,e,s,h);g()}}},entity:function(){return d(this.entities.literal)||d(this.entities.variable)||d(this.entities.url)||d(this.entities.call)||d(this.entities.keyword)||d(this.entities.javascript)||d(this.comment)},end:function(){return d(";")||k("}")},alpha:function(){var b;if(d(/^\(opacity=/i)&&(b=d(/^\d+/)||d(this.entities.variable)))return p(")"),new l.Alpha(b)},element:function(){var b,f,c;f=d(this.combinator);b=d(/^(?:\d+\.\d+|\d+)%/)||
d(/^(?:[.#]?|:*)(?:[\w-]|[^\x00-\x9f]|\\(?:[A-Fa-f0-9]{1,6} ?|[^A-Fa-f0-9]))+/)||d("*")||d("&")||d(this.attribute)||d(/^\([^()@]+\)/)||d(/^[\.#](?=@)/)||d(this.entities.variableCurly);if(!b&&d("(")&&(c=d(this.entities.variableCurly)||d(this.entities.variable)||d(this.selector))&&d(")"))b=new l.Paren(c);if(b)return new l.Element(f,b,m)},combinator:function(){var b=r.charAt(m);if(">"===b||"+"===b||"~"===b||"|"===b){for(m++;r.charAt(m).match(/\s/);)m++;return new l.Combinator(b)}return r.charAt(m-1).match(/\s/)?
new l.Combinator(" "):new l.Combinator(null)},selector:function(){var b,f=[],c;if(d("("))return b=d(this.entity),!d(")")?null:new l.Selector([new l.Element("",b,m)]);for(;(b=d(this.element))&&!(c=r.charAt(m),f.push(b),"{"===c||"}"===c||";"===c||","===c||")"===c););if(0<f.length)return new l.Selector(f)},attribute:function(){var b="",f,c,g;if(d("[")){if(f=d(/^(?:[_A-Za-z0-9-]|\\.)+/)||d(this.entities.quoted))b=(g=d(/^[|~*$^]?=/))&&(c=d(this.entities.quoted)||d(/^[\w-]+/))?[f,g,c.toCSS?c.toCSS():c].join(""):
f;if(d("]")&&b)return"["+b+"]"}},block:function(){var b;if(d("{")&&(b=d(this.primary))&&d("}"))return b},ruleset:function(){var f=[],e,p,n;b();for(c.dumpLineNumbers&&(n=y(m,r,c));e=d(this.selector);){f.push(e);d(this.comment);if(!d(","))break;d(this.comment)}if(0<f.length&&(p=d(this.block)))return f=new l.Ruleset(f,p,c.strictImports),c.dumpLineNumbers&&(f.debugInfo=n),f;t=m;g()},rule:function(){var f,c;f=r.charAt(m);var e;b();if(!("."===f||"#"===f||"&"===f))if(f=d(this.variable)||d(this.property)){"@"!=
f.charAt(0)&&(c=/^([^@+\/'"*`(;{}-]*);/.exec(x[v]))?(m+=c[0].length-1,c=new l.Anonymous(c[1])):c="font"===f?d(this.font):d(this.value);e=d(this.important);if(c&&d(this.end))return new l.Rule(f,c,e,A);t=m;g()}},"import":function(){var f,e,p=m;b();var n=d(/^@import(?:-(once))?\s+/);if(n&&(f=d(this.entities.quoted)||d(this.entities.url)))if(e=d(this.mediaFeatures),d(";"))return new l.Import(f,F,e,"once"===n[1],p,c.rootpath);g()},mediaFeature:function(){var b,f,c=[];do if(b=d(this.entities.keyword))c.push(b);
else if(d("("))if(f=d(this.property),b=d(this.entity),d(")"))if(f&&b)c.push(new l.Paren(new l.Rule(f,b,null,m,!0)));else if(b)c.push(new l.Paren(b));else return null;else return null;while(b);if(0<c.length)return new l.Expression(c)},mediaFeatures:function(){var b,f=[];do if(b=d(this.mediaFeature)){if(f.push(b),!d(","))break}else if(b=d(this.entities.variable))if(f.push(b),!d(","))break;while(b);return 0<f.length?f:null},media:function(){var b,f,g;c.dumpLineNumbers&&(g=y(m,r,c));if(d(/^@media/)&&
(b=d(this.mediaFeatures),f=d(this.block)))return b=new l.Media(f,b),c.dumpLineNumbers&&(b.debugInfo=g),b},directive:function(){var f,e,p,n,k;if("@"===r.charAt(m)){if(e=d(this["import"])||d(this.media))return e;b();if(f=d(/^@[a-z-]+/)){e=f;"-"==f.charAt(1)&&0<f.indexOf("-",2)&&(e="@"+f.slice(f.indexOf("-",2)+1));switch(e){case "@font-face":p=!0;break;case "@viewport":case "@top-left":case "@top-left-corner":case "@top-center":case "@top-right":case "@top-right-corner":case "@bottom-left":case "@bottom-left-corner":case "@bottom-center":case "@bottom-right":case "@bottom-right-corner":case "@left-top":case "@left-middle":case "@left-bottom":case "@right-top":case "@right-middle":case "@right-bottom":p=
!0;break;case "@page":case "@document":case "@supports":case "@keyframes":n=p=!0;break;case "@namespace":case "@alternate":k=!0}n&&(f+=" "+(d(/^[^{]+/)||"").trim());if(p){if(p=d(this.block))return new l.Directive(f,p)}else if((e=k?d(this.expression):d(this.entity))&&d(";"))return f=new l.Directive(f,e),c.dumpLineNumbers&&(f.debugInfo=y(m,r,c)),f;g()}}},font:function(){for(var b=[],f=[],c;c=d(this.shorthand)||d(this.entity);)f.push(c);b.push(new l.Expression(f));if(d(","))for(;(c=d(this.expression))&&
!(b.push(c),!d(",")););return new l.Value(b)},value:function(){for(var b,f=[];(b=d(this.expression))&&!(f.push(b),!d(",")););if(0<f.length)return new l.Value(f)},important:function(){if("!"===r.charAt(m))return d(/^! *important/)},sub:function(){var b;if(d("(")&&(b=d(this.expression))&&d(")"))return b},multiplication:function(){var b,f,c,g;if(b=d(this.operand)){for(;!k(/^\/[*\/]/)&&(c=d("/")||d("*"))&&(f=d(this.operand));)g=new l.Operation(c,[g||b,f]);return g||b}},addition:function(){var b,c,g,e;
if(b=d(this.multiplication)){for(;(g=d(/^[-+]\s+/)||!f(r.charAt(m-1))&&(d("+")||d("-")))&&(c=d(this.multiplication));)e=new l.Operation(g,[e||b,c]);return e||b}},conditions:function(){var b,f,c=m,g;if(b=d(this.condition)){for(;d(",")&&(f=d(this.condition));)g=new l.Condition("or",g||b,f,c);return g||b}},condition:function(){var b,f,c,g,e=m,k=!1;d(/^not/)&&(k=!0);p("(");if(b=d(this.addition)||d(this.entities.keyword)||d(this.entities.quoted))return(g=d(/^(?:>=|=<|[<=>])/))?(f=d(this.addition)||d(this.entities.keyword)||
d(this.entities.quoted))?c=new l.Condition(g,b,f,e,k):n("expected expression"):c=new l.Condition("=",b,new l.Keyword("true"),e,k),p(")"),d(/^and/)?new l.Condition("and",c,d(this.condition)):c},operand:function(){var b,f=r.charAt(m+1);if("-"===r.charAt(m)&&("@"===f||"("===f))b=d("-");f=d(this.sub)||d(this.entities.dimension)||d(this.entities.color)||d(this.entities.variable)||d(this.entities.call);return b?new l.Operation("*",[new l.Dimension(-1),f]):f},expression:function(){for(var b,f=[];b=d(this.addition)||
d(this.entity);)f.push(b);if(0<f.length)return new l.Expression(f)},property:function(){var b;if(b=d(/^(\*?-?[_a-z0-9-]+)\s*:/))return b[1]}}}};if("browser"===h.mode||"rhino"===h.mode)h.Parser.importer=function(c,b,g,e){!/^([a-z-]+:)?\//.test(c)&&0<b.length&&(c=b[0]+c);N({href:c,title:c,type:e.mime,contents:e.contents,files:e.files,rootpath:e.rootpath,entryPath:e.entryPath,relativeUrls:e.relativeUrls},function(f,d,c,n,k,s){f&&"function"===typeof e.errback?e.errback.call(null,s,b,g,e):g.call(null,
f,d,s)},!0)};(function(c){function b(b){return c.functions.hsla(b.h,b.s,b.l,b.a)}function g(b){if(b instanceof c.Dimension)return parseFloat("%"==b.unit?b.value/100:b.value);if("number"===typeof b)return b;throw{error:"RuntimeError",message:"color functions take numbers as parameters"};}function e(b){return Math.min(1,Math.max(0,b))}c.functions={rgb:function(b,d,c){return this.rgba(b,d,c,1)},rgba:function(b,d,e,n){b=[b,d,e].map(function(b){b=b instanceof c.Dimension&&"%"==b.unit?parseFloat(256*b.value/
100):g(b);return b});n=g(n);return new c.Color(b,n)},hsl:function(b,d,c){return this.hsla(b,d,c,1)},hsla:function(b,d,c,e){function k(b){b=0>b?b+1:1<b?b-1:b;return 1>6*b?h+6*(s-h)*b:1>2*b?s:2>3*b?h+6*(s-h)*(2/3-b):h}b=g(b)%360/360;d=g(d);c=g(c);e=g(e);var s=0.5>=c?c*(d+1):c+d-c*d,h=2*c-s;return this.rgba(255*k(b+1/3),255*k(b),255*k(b-1/3),e)},hsv:function(b,d,c){return this.hsva(b,d,c,1)},hsva:function(b,d,c,e){b=360*(g(b)%360/360);d=g(d);c=g(c);e=g(e);var k;k=Math.floor(b/60%6);b=b/60-k;d=[c,c*(1-
d),c*(1-b*d),c*(1-(1-b)*d)];c=[[0,3,1],[2,0,1],[1,0,3],[1,2,0],[3,1,0],[0,1,2]];return this.rgba(255*d[c[k][0]],255*d[c[k][1]],255*d[c[k][2]],e)},hue:function(b){return new c.Dimension(Math.round(b.toHSL().h))},saturation:function(b){return new c.Dimension(Math.round(100*b.toHSL().s),"%")},lightness:function(b){return new c.Dimension(Math.round(100*b.toHSL().l),"%")},red:function(b){return new c.Dimension(b.rgb[0])},green:function(b){return new c.Dimension(b.rgb[1])},blue:function(b){return new c.Dimension(b.rgb[2])},
alpha:function(b){return new c.Dimension(b.toHSL().a)},luma:function(b){return new c.Dimension(Math.round(100*(0.2126*(b.rgb[0]/255)+0.7152*(b.rgb[1]/255)+0.0722*(b.rgb[2]/255))*b.alpha),"%")},saturate:function(f,d){var c=f.toHSL();c.s+=d.value/100;c.s=e(c.s);return b(c)},desaturate:function(f,d){var c=f.toHSL();c.s-=d.value/100;c.s=e(c.s);return b(c)},lighten:function(f,d){var c=f.toHSL();c.l+=d.value/100;c.l=e(c.l);return b(c)},darken:function(f,d){var c=f.toHSL();c.l-=d.value/100;c.l=e(c.l);return b(c)},
fadein:function(f,d){var c=f.toHSL();c.a+=d.value/100;c.a=e(c.a);return b(c)},fadeout:function(c,d){var g=c.toHSL();g.a-=d.value/100;g.a=e(g.a);return b(g)},fade:function(c,d){var g=c.toHSL();g.a=d.value/100;g.a=e(g.a);return b(g)},spin:function(c,d){var g=c.toHSL(),e=(g.h+d.value)%360;g.h=0>e?360+e:e;return b(g)},mix:function(b,d,g){g||(g=new c.Dimension(50));g=g.value/100;var e=2*g-1,k=b.toHSL().a-d.toHSL().a,e=((-1==e*k?e:(e+k)/(1+e*k))+1)/2,k=1-e;return new c.Color([b.rgb[0]*e+d.rgb[0]*k,b.rgb[1]*
e+d.rgb[1]*k,b.rgb[2]*e+d.rgb[2]*k],b.alpha*g+d.alpha*(1-g))},greyscale:function(b){return this.desaturate(b,new c.Dimension(100))},contrast:function(b,d,c,g){if(!b.rgb)return null;"undefined"===typeof c&&(c=this.rgba(255,255,255,1));"undefined"===typeof d&&(d=this.rgba(0,0,0,1));g="undefined"===typeof g?0.43:g.value;return(0.2126*(b.rgb[0]/255)+0.7152*(b.rgb[1]/255)+0.0722*(b.rgb[2]/255))*b.alpha<g?c:d},e:function(b){return new c.Anonymous(b instanceof c.JavaScript?b.evaluated:b)},escape:function(b){return new c.Anonymous(encodeURI(b.value).replace(/=/g,
"%3D").replace(/:/g,"%3A").replace(/#/g,"%23").replace(/;/g,"%3B").replace(/\(/g,"%28").replace(/\)/g,"%29"))},"%":function(b){for(var d=Array.prototype.slice.call(arguments,1),g=b.value,e=0;e<d.length;e++)g=g.replace(/%[sda]/i,function(b){var c=b.match(/s/i)?d[e].value:d[e].toCSS();return b.match(/[A-Z]$/)?encodeURIComponent(c):c});g=g.replace(/%%/g,"%");return new c.Quoted('"'+g+'"',g)},unit:function(b,d){return new c.Dimension(b.value,d?d.toCSS():"")},round:function(b,d){var c="undefined"===typeof d?
0:d.value;return this._math(function(b){return b.toFixed(c)},b)},ceil:function(b){return this._math(Math.ceil,b)},floor:function(b){return this._math(Math.floor,b)},_math:function(b,d){if(d instanceof c.Dimension)return new c.Dimension(b(parseFloat(d.value)),d.unit);if("number"===typeof d)return b(d);throw{type:"Argument",message:"argument must be a number"};},argb:function(b){return new c.Anonymous(b.toARGB())},percentage:function(b){return new c.Dimension(100*b.value,"%")},color:function(b){if(b instanceof
c.Quoted)return new c.Color(b.value.slice(1));throw{type:"Argument",message:"argument must be a string"};},iscolor:function(b){return this._isa(b,c.Color)},isnumber:function(b){return this._isa(b,c.Dimension)},isstring:function(b){return this._isa(b,c.Quoted)},iskeyword:function(b){return this._isa(b,c.Keyword)},isurl:function(b){return this._isa(b,c.URL)},ispixel:function(b){return b instanceof c.Dimension&&"px"===b.unit?c.True:c.False},ispercentage:function(b){return b instanceof c.Dimension&&"%"===
b.unit?c.True:c.False},isem:function(b){return b instanceof c.Dimension&&"em"===b.unit?c.True:c.False},_isa:function(b,d){return b instanceof d?c.True:c.False},multiply:function(b,d){return this.rgb(b.rgb[0]*d.rgb[0]/255,b.rgb[1]*d.rgb[1]/255,b.rgb[2]*d.rgb[2]/255)},screen:function(b,d){return this.rgb(255-(255-b.rgb[0])*(255-d.rgb[0])/255,255-(255-b.rgb[1])*(255-d.rgb[1])/255,255-(255-b.rgb[2])*(255-d.rgb[2])/255)},overlay:function(b,d){return this.rgb(128>b.rgb[0]?2*b.rgb[0]*d.rgb[0]/255:255-2*
(255-b.rgb[0])*(255-d.rgb[0])/255,128>b.rgb[1]?2*b.rgb[1]*d.rgb[1]/255:255-2*(255-b.rgb[1])*(255-d.rgb[1])/255,128>b.rgb[2]?2*b.rgb[2]*d.rgb[2]/255:255-2*(255-b.rgb[2])*(255-d.rgb[2])/255)},softlight:function(b,d){var c=d.rgb[0]*b.rgb[0]/255,g=c+b.rgb[0]*(255-(255-b.rgb[0])*(255-d.rgb[0])/255-c)/255,c=d.rgb[1]*b.rgb[1]/255,e=c+b.rgb[1]*(255-(255-b.rgb[1])*(255-d.rgb[1])/255-c)/255,c=d.rgb[2]*b.rgb[2]/255;return this.rgb(g,e,c+b.rgb[2]*(255-(255-b.rgb[2])*(255-d.rgb[2])/255-c)/255)},hardlight:function(b,
d){return this.rgb(128>d.rgb[0]?2*d.rgb[0]*b.rgb[0]/255:255-2*(255-d.rgb[0])*(255-b.rgb[0])/255,128>d.rgb[1]?2*d.rgb[1]*b.rgb[1]/255:255-2*(255-d.rgb[1])*(255-b.rgb[1])/255,128>d.rgb[2]?2*d.rgb[2]*b.rgb[2]/255:255-2*(255-d.rgb[2])*(255-b.rgb[2])/255)},difference:function(b,d){var c=Math.abs(b.rgb[0]-d.rgb[0]),g=Math.abs(b.rgb[1]-d.rgb[1]),e=Math.abs(b.rgb[2]-d.rgb[2]);return this.rgb(c,g,e)},exclusion:function(b,d){return this.rgb(b.rgb[0]+d.rgb[0]*(255-b.rgb[0]-b.rgb[0])/255,b.rgb[1]+d.rgb[1]*(255-
b.rgb[1]-b.rgb[1])/255,b.rgb[2]+d.rgb[2]*(255-b.rgb[2]-b.rgb[2])/255)},average:function(b,d){return this.rgb((b.rgb[0]+d.rgb[0])/2,(b.rgb[1]+d.rgb[1])/2,(b.rgb[2]+d.rgb[2])/2)},negation:function(b,d){var c=255-Math.abs(255-d.rgb[0]-b.rgb[0]),g=255-Math.abs(255-d.rgb[1]-b.rgb[1]),e=255-Math.abs(255-d.rgb[2]-b.rgb[2]);return this.rgb(c,g,e)},tint:function(b,d){return this.mix(this.rgb(255,255,255),b,d)},shade:function(b,d){return this.mix(this.rgb(0,0,0),b,d)}}})(q("./tree"));(function(c){c.colors=
{aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgrey:"#a9a9a9",darkgreen:"#006400",
darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",
gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",grey:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",
lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",
navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",
sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"}})(q("./tree"));(function(c){c.Alpha=function(b){this.value=b};c.Alpha.prototype={toCSS:function(){return"alpha(opacity="+(this.value.toCSS?
this.value.toCSS():this.value)+")"},eval:function(b){this.value.eval&&(this.value=this.value.eval(b));return this}}})(q("../tree"));(function(c){c.Anonymous=function(b){this.value=b.value||b};c.Anonymous.prototype={toCSS:function(){return this.value},eval:function(){return this},compare:function(b){if(!b.toCSS)return-1;var c=this.toCSS();b=b.toCSS();return c===b?0:c<b?-1:1}}})(q("../tree"));(function(c){c.Assignment=function(b,c){this.key=b;this.value=c};c.Assignment.prototype={toCSS:function(){return this.key+
"="+(this.value.toCSS?this.value.toCSS():this.value)},eval:function(b){return this.value.eval?new c.Assignment(this.key,this.value.eval(b)):this}}})(q("../tree"));(function(c){c.Call=function(b,c,e,f){this.name=b;this.args=c;this.index=e;this.filename=f};c.Call.prototype={eval:function(b){var g=this.args.map(function(d){return d.eval(b)}),e;if(this.name in c.functions)try{if(e=c.functions[this.name].apply(c.functions,g),null!=e)return e}catch(f){throw{type:f.type||"Runtime",message:"error evaluating function `"+
this.name+"`"+(f.message?": "+f.message:""),index:this.index,filename:this.filename};}return new c.Anonymous(this.name+"("+g.map(function(d){return d.toCSS(b)}).join(", ")+")")},toCSS:function(b){return this.eval(b).toCSS()}}})(q("../tree"));(function(c){c.Color=function(b,c){Array.isArray(b)?this.rgb=b:this.rgb=6==b.length?b.match(/.{2}/g).map(function(b){return parseInt(b,16)}):b.split("").map(function(b){return parseInt(b+b,16)});this.alpha="number"===typeof c?c:1};c.Color.prototype={eval:function(){return this},
toCSS:function(){return 1>this.alpha?"rgba("+this.rgb.map(function(b){return Math.round(b)}).concat(this.alpha).join(", ")+")":"#"+this.rgb.map(function(b){b=Math.round(b);b=(255<b?255:0>b?0:b).toString(16);return 1===b.length?"0"+b:b}).join("")},operate:function(b,g){var e=[];g instanceof c.Color||(g=g.toColor());for(var f=0;3>f;f++)e[f]=c.operate(b,this.rgb[f],g.rgb[f]);return new c.Color(e,this.alpha+g.alpha)},toHSL:function(){var b=this.rgb[0]/255,c=this.rgb[1]/255,e=this.rgb[2]/255,f=this.alpha,
d=Math.max(b,c,e),p=Math.min(b,c,e),n,k=(d+p)/2,s=d-p;if(d===p)n=p=0;else{p=0.5<k?s/(2-d-p):s/(d+p);switch(d){case b:n=(c-e)/s+(c<e?6:0);break;case c:n=(e-b)/s+2;break;case e:n=(b-c)/s+4}n/=6}return{h:360*n,s:p,l:k,a:f}},toARGB:function(){return"#"+[Math.round(255*this.alpha)].concat(this.rgb).map(function(b){b=Math.round(b);b=(255<b?255:0>b?0:b).toString(16);return 1===b.length?"0"+b:b}).join("")},compare:function(b){return!b.rgb?-1:b.rgb[0]===this.rgb[0]&&b.rgb[1]===this.rgb[1]&&b.rgb[2]===this.rgb[2]&&
b.alpha===this.alpha?0:-1}}})(q("../tree"));(function(c){c.Comment=function(b,c){this.value=b;this.silent=!!c};c.Comment.prototype={toCSS:function(b){return this.value},eval:function(){return this}}})(q("../tree"));(function(c){c.Condition=function(b,c,e,f,d){this.op=b.trim();this.lvalue=c;this.rvalue=e;this.index=f;this.negate=d};c.Condition.prototype.eval=function(b){var c=this.lvalue.eval(b),e=this.rvalue.eval(b),f=this.index,d;d=function(b){switch(b){case "and":return c&&e;case "or":return c||
e;default:if(c.compare)d=c.compare(e);else if(e.compare)d=e.compare(c);else throw{type:"Type",message:"Unable to perform comparison",index:f};switch(d){case -1:return"<"===b||"=<"===b;case 0:return"="===b||">="===b||"=<"===b;case 1:return">"===b||">="===b}}}(this.op);return this.negate?!d:d}})(q("../tree"));(function(c){c.Dimension=function(b,c){this.value=parseFloat(b);this.unit=c||null};c.Dimension.prototype={eval:function(){return this},toColor:function(){return new c.Color([this.value,this.value,
this.value])},toCSS:function(){return this.value+this.unit},operate:function(b,g){return new c.Dimension(c.operate(b,this.value,g.value),this.unit||g.unit)},compare:function(b){return b instanceof c.Dimension?b.value>this.value?-1:b.value<this.value?1:b.unit&&this.unit!==b.unit?-1:0:-1}}})(q("../tree"));(function(c){c.Directive=function(b,g){this.name=b;Array.isArray(g)?(this.ruleset=new c.Ruleset([],g),this.ruleset.allowImports=!0):this.value=g};c.Directive.prototype={toCSS:function(b,c){return this.ruleset?
(this.ruleset.root=!0,this.name+(c.compress?"{":" {\n  ")+this.ruleset.toCSS(b,c).trim().replace(/\n/g,"\n  ")+(c.compress?"}":"\n}\n")):this.name+" "+this.value.toCSS()+";\n"},eval:function(b){var g=this;this.ruleset&&(b.frames.unshift(this),g=new c.Directive(this.name),g.ruleset=this.ruleset.eval(b),b.frames.shift());return g},variable:function(b){return c.Ruleset.prototype.variable.call(this.ruleset,b)},find:function(){return c.Ruleset.prototype.find.apply(this.ruleset,arguments)},rulesets:function(){return c.Ruleset.prototype.rulesets.apply(this.ruleset)}}})(q("../tree"));
(function(c){c.Element=function(b,g,e){this.combinator=b instanceof c.Combinator?b:new c.Combinator(b);this.value="string"===typeof g?g.trim():g?g:"";this.index=e};c.Element.prototype.eval=function(b){return new c.Element(this.combinator,this.value.eval?this.value.eval(b):this.value,this.index)};c.Element.prototype.toCSS=function(b){var c=this.value.toCSS?this.value.toCSS(b):this.value;return""==c&&"&"==this.combinator.value.charAt(0)?"":this.combinator.toCSS(b||{})+c};c.Combinator=function(b){this.value=
" "===b?" ":b?b.trim():""};c.Combinator.prototype.toCSS=function(b){return{"":""," ":" ",":":" :","+":b.compress?"+":" + ","~":b.compress?"~":" ~ ",">":b.compress?">":" > ","|":b.compress?"|":" | "}[this.value]}})(q("../tree"));(function(c){c.Expression=function(b){this.value=b};c.Expression.prototype={eval:function(b){return 1<this.value.length?new c.Expression(this.value.map(function(c){return c.eval(b)})):1===this.value.length?this.value[0].eval(b):this},toCSS:function(b){return this.value.map(function(c){return c.toCSS?
c.toCSS(b):""}).join(" ")}}})(q("../tree"));(function(c){c.Import=function(b,g,e,f,d,p){var n=this;this.once=f;this.index=d;this._path=b;this.features=e&&new c.Value(e);this.rootpath=p;this.path=b instanceof c.Quoted?/(\.[a-z]*$)|([\?;].*)$/.test(b.value)?b.value:b.value+".less":b.value.value||b.value;(this.css=/css([\?;].*)?$/.test(this.path))||g.push(this.path,function(b,g,e){b&&(b.index=d);e&&n.once&&(n.skip=e);n.root=g||new c.Ruleset([],[])})};c.Import.prototype={toCSS:function(b){b=this.features?
" "+this.features.toCSS(b):"";return this.css?("string"===typeof this._path.value&&!/^(?:[a-z-]+:|\/)/.test(this._path.value)&&(this._path.value=this.rootpath+this._path.value),"@import "+this._path.toCSS()+b+";\n"):""},eval:function(b){var g;this.features&&this.features.eval(b);if(this.skip)return[];if(this.css)return this;g=new c.Ruleset([],this.root.rules.slice(0));g.evalImports(b);return this.features?new c.Media(g.rules,this.features.value):g.rules}}})(q("../tree"));(function(c){c.JavaScript=
function(b,c,e){this.escaped=e;this.expression=b;this.index=c};c.JavaScript.prototype={eval:function(b){var g,e=this,f={},d=this.expression.replace(/@\{([\w-]+)\}/g,function(d,g){return c.jsify((new c.Variable("@"+g,e.index)).eval(b))});try{d=new Function("return ("+d+")")}catch(p){throw{message:"JavaScript evaluation error: `"+d+"`",index:this.index};}for(var n in b.frames[0].variables())f[n.slice(1)]={value:b.frames[0].variables()[n].value,toJS:function(){return this.value.eval(b).toCSS()}};try{g=
d.call(f)}catch(k){throw{message:"JavaScript evaluation error: '"+k.name+": "+k.message+"'",index:this.index};}return"string"===typeof g?new c.Quoted('"'+g+'"',g,this.escaped,this.index):Array.isArray(g)?new c.Anonymous(g.join(", ")):new c.Anonymous(g)}}})(q("../tree"));(function(c){c.Keyword=function(b){this.value=b};c.Keyword.prototype={eval:function(){return this},toCSS:function(){return this.value},compare:function(b){return b instanceof c.Keyword?b.value===this.value?0:1:-1}};c.True=new c.Keyword("true");
c.False=new c.Keyword("false")})(q("../tree"));(function(c){c.Media=function(b,g){var e=this.emptySelectors();this.features=new c.Value(g);this.ruleset=new c.Ruleset(e,b);this.ruleset.allowImports=!0};c.Media.prototype={toCSS:function(b,c){var e=this.features.toCSS(c);this.ruleset.root=0===b.length||b[0].multiMedia;return"@media "+e+(c.compress?"{":" {\n  ")+this.ruleset.toCSS(b,c).trim().replace(/\n/g,"\n  ")+(c.compress?"}":"\n}\n")},eval:function(b){b.mediaBlocks||(b.mediaBlocks=[],b.mediaPath=
[]);var g=new c.Media([],[]);this.debugInfo&&(this.ruleset.debugInfo=this.debugInfo,g.debugInfo=this.debugInfo);g.features=this.features.eval(b);b.mediaPath.push(g);b.mediaBlocks.push(g);b.frames.unshift(this.ruleset);g.ruleset=this.ruleset.eval(b);b.frames.shift();b.mediaPath.pop();return 0===b.mediaPath.length?g.evalTop(b):g.evalNested(b)},variable:function(b){return c.Ruleset.prototype.variable.call(this.ruleset,b)},find:function(){return c.Ruleset.prototype.find.apply(this.ruleset,arguments)},
rulesets:function(){return c.Ruleset.prototype.rulesets.apply(this.ruleset)},emptySelectors:function(){var b=new c.Element("","&",0);return[new c.Selector([b])]},evalTop:function(b){var g=this;1<b.mediaBlocks.length&&(g=this.emptySelectors(),g=new c.Ruleset(g,b.mediaBlocks),g.multiMedia=!0);delete b.mediaBlocks;delete b.mediaPath;return g},evalNested:function(b){var g,e=b.mediaPath.concat([this]);for(g=0;g<e.length;g++)b=e[g].features instanceof c.Value?e[g].features.value:e[g].features,e[g]=Array.isArray(b)?
b:[b];this.features=new c.Value(this.permute(e).map(function(b){b=b.map(function(b){return b.toCSS?b:new c.Anonymous(b)});for(g=b.length-1;0<g;g--)b.splice(g,0,new c.Anonymous("and"));return new c.Expression(b)}));return new c.Ruleset([],[])},permute:function(b){if(0===b.length)return[];if(1===b.length)return b[0];for(var c=[],e=this.permute(b.slice(1)),f=0;f<e.length;f++)for(var d=0;d<b[0].length;d++)c.push([b[0][d]].concat(e[f]));return c},bubbleSelectors:function(b){this.ruleset=new c.Ruleset(b.slice(0),
[this.ruleset])}}})(q("../tree"));(function(c){c.mixin={};c.mixin.Call=function(b,g,e,f,d){this.selector=new c.Selector(b);this.arguments=g;this.index=e;this.filename=f;this.important=d};c.mixin.Call.prototype={eval:function(b){var g,e,f,d=[],p=!1,n,k,h,l,q;f=this.arguments&&this.arguments.map(function(c){return{name:c.name,value:c.value.eval(b)}});for(n=0;n<b.frames.length;n++)if(0<(g=b.frames[n].find(this.selector)).length){q=!0;for(k=0;k<g.length;k++){e=g[k];l=!1;for(h=0;h<b.frames.length;h++)if(!(e instanceof
c.mixin.Definition)&&e===(b.frames[h].originalRuleset||b.frames[h])){l=!0;break}if(!l&&e.matchArgs(f,b)){if(!e.matchCondition||e.matchCondition(f,b))try{Array.prototype.push.apply(d,e.eval(b,f,this.important).rules)}catch(r){throw{message:r.message,index:this.index,filename:this.filename,stack:r.stack};}p=!0}}if(p)return d}if(q)throw{type:"Runtime",message:"No matching definition was found for `"+this.selector.toCSS().trim()+"("+(f?f.map(function(b){var c="";b.name&&(c+=b.name+":");return c=b.value.toCSS?
c+b.value.toCSS():c+"???"}).join(", "):"")+")`",index:this.index,filename:this.filename};throw{type:"Name",message:this.selector.toCSS().trim()+" is undefined",index:this.index,filename:this.filename};}};c.mixin.Definition=function(b,g,e,f,d){this.name=b;this.selectors=[new c.Selector([new c.Element(null,b)])];this.params=g;this.condition=f;this.variadic=d;this.arity=g.length;this.rules=e;this._lookups={};this.required=g.reduce(function(b,c){return!c.name||c.name&&!c.value?b+1:b},0);this.parent=c.Ruleset.prototype;
this.frames=[]};c.mixin.Definition.prototype={toCSS:function(){return""},variable:function(b){return this.parent.variable.call(this,b)},variables:function(){return this.parent.variables.call(this)},find:function(){return this.parent.find.apply(this,arguments)},rulesets:function(){return this.parent.rulesets.apply(this)},evalParams:function(b,g,e,f){var d=new c.Ruleset(null,[]),p,n=this.params.slice(0),k,h,l,q;if(e){e=e.slice(0);for(k=0;k<e.length;k++)if(l=(p=e[k])&&p.name){q=!1;for(h=0;h<n.length;h++)if(!f[h]&&
l===n[h].name){f[h]=p.value.eval(b);d.rules.unshift(new c.Rule(l,p.value.eval(b)));q=!0;break}if(q)e.splice(k,1),k--;else throw{type:"Runtime",message:"Named argument for "+this.name+" "+e[k].name+" not found"};}}for(k=q=0;k<n.length;k++)if(!f[k]){p=e&&e[q];if(l=n[k].name)if(n[k].variadic&&e){p=[];for(h=q;h<e.length;h++)p.push(e[h].value.eval(b));d.rules.unshift(new c.Rule(l,(new c.Expression(p)).eval(b)))}else{if(h=p&&p.value)h=h.eval(b);else if(n[k].value)h=n[k].value.eval(g);else throw{type:"Runtime",
message:"wrong number of arguments for "+this.name+" ("+e.length+" for "+this.arity+")"};d.rules.unshift(new c.Rule(l,h));f[k]=h}if(n[k].variadic&&e)for(h=q;h<e.length;h++)f[h]=e[h].value.eval(b);q++}return d},eval:function(b,g,e){var f=[],d=this.frames.concat(b.frames);g=this.evalParams(b,{frames:d},g,f);g.rules.unshift(new c.Rule("@arguments",(new c.Expression(f)).eval(b)));b=e?this.parent.makeImportant.apply(this).rules:this.rules.slice(0);d=(new c.Ruleset(null,b)).eval({frames:[this,g].concat(d)});
d.originalRuleset=this;return d},matchCondition:function(b,c){return this.condition&&!this.condition.eval({frames:[this.evalParams(c,{frames:this.frames.concat(c.frames)},b,[])].concat(c.frames)})?!1:!0},matchArgs:function(b,c){var e=b&&b.length||0;if(!this.variadic&&(e<this.required||e>this.params.length||0<this.required&&e>this.params.length))return!1;for(var e=Math.min(e,this.arity),f=0;f<e;f++)if(!this.params[f].name&&!this.params[f].variadic&&b[f].value.eval(c).toCSS()!=this.params[f].value.eval(c).toCSS())return!1;
return!0}}})(q("../tree"));(function(c){c.Operation=function(b,c){this.op=b.trim();this.operands=c};c.Operation.prototype.eval=function(b){var g=this.operands[0].eval(b);b=this.operands[1].eval(b);var e;if(g instanceof c.Dimension&&b instanceof c.Color)if("*"===this.op||"+"===this.op)e=b,b=g,g=e;else throw{name:"OperationError",message:"Can't substract or divide a color from a number"};if(!g.operate)throw{name:"OperationError",message:"Operation on an invalid type"};return g.operate(this.op,b)};c.operate=
function(b,c,e){switch(b){case "+":return c+e;case "-":return c-e;case "*":return c*e;case "/":return c/e}}})(q("../tree"));(function(c){c.Paren=function(b){this.value=b};c.Paren.prototype={toCSS:function(b){return"("+this.value.toCSS(b)+")"},eval:function(b){return new c.Paren(this.value.eval(b))}}})(q("../tree"));(function(c){c.Quoted=function(b,c,e,f){this.escaped=e;this.value=c||"";this.quote=b.charAt(0);this.index=f};c.Quoted.prototype={toCSS:function(){return this.escaped?this.value:this.quote+
this.value+this.quote},eval:function(b){var g=this,e=this.value.replace(/`([^`]+)`/g,function(e,d){return(new c.JavaScript(d,g.index,!0)).eval(b).value}).replace(/@\{([\w-]+)\}/g,function(e,d){var h=(new c.Variable("@"+d,g.index)).eval(b);return h instanceof c.Quoted?h.value:h.toCSS()});return new c.Quoted(this.quote+e+this.quote,e,this.escaped,this.index)},compare:function(b){if(!b.toCSS)return-1;var c=this.toCSS();b=b.toCSS();return c===b?0:c<b?-1:1}}})(q("../tree"));(function(c){c.Ratio=function(b){this.value=
b};c.Ratio.prototype={toCSS:function(b){return this.value},eval:function(){return this}}})(q("../tree"));(function(c){c.Rule=function(b,g,e,f,d){this.name=b;this.value=g instanceof c.Value?g:new c.Value([g]);this.important=e?" "+e.trim():"";this.index=f;this.inline=d||!1;"@"===b.charAt(0)?this.variable=!0:this.variable=!1};c.Rule.prototype.toCSS=function(b){return this.variable?"":this.name+(b.compress?":":": ")+this.value.toCSS(b)+this.important+(this.inline?"":";")};c.Rule.prototype.eval=function(b){return new c.Rule(this.name,
this.value.eval(b),this.important,this.index,this.inline)};c.Rule.prototype.makeImportant=function(){return new c.Rule(this.name,this.value,"!important",this.index,this.inline)};c.Shorthand=function(b,c){this.a=b;this.b=c};c.Shorthand.prototype={toCSS:function(b){return this.a.toCSS(b)+"/"+this.b.toCSS(b)},eval:function(){return this}}})(q("../tree"));(function(c){c.Ruleset=function(b,c,e){this.selectors=b;this.rules=c;this._lookups={};this.strictImports=e};c.Ruleset.prototype={eval:function(b){var g=
this.selectors&&this.selectors.map(function(c){return c.eval(b)}),e=new c.Ruleset(g,this.rules.slice(0),this.strictImports),f;e.originalRuleset=this;e.root=this.root;e.allowImports=this.allowImports;this.debugInfo&&(e.debugInfo=this.debugInfo);b.frames.unshift(e);(e.root||e.allowImports||!e.strictImports)&&e.evalImports(b);for(var d=0;d<e.rules.length;d++)e.rules[d]instanceof c.mixin.Definition&&(e.rules[d].frames=b.frames.slice(0));for(var h=b.mediaBlocks&&b.mediaBlocks.length||0,d=0;d<e.rules.length;d++)e.rules[d]instanceof
c.mixin.Call&&(f=e.rules[d].eval(b),e.rules.splice.apply(e.rules,[d,1].concat(f)),d+=f.length-1,e.resetCache());for(d=0;d<e.rules.length;d++)f=e.rules[d],f instanceof c.mixin.Definition||(e.rules[d]=f.eval?f.eval(b):f);b.frames.shift();if(b.mediaBlocks)for(d=h;d<b.mediaBlocks.length;d++)b.mediaBlocks[d].bubbleSelectors(g);return e},evalImports:function(b){var g,e;for(g=0;g<this.rules.length;g++)this.rules[g]instanceof c.Import&&(e=this.rules[g].eval(b),"number"===typeof e.length?(this.rules.splice.apply(this.rules,
[g,1].concat(e)),g+=e.length-1):this.rules.splice(g,1,e),this.resetCache())},makeImportant:function(){return new c.Ruleset(this.selectors,this.rules.map(function(b){return b.makeImportant?b.makeImportant():b}),this.strictImports)},matchArgs:function(b){return!b||0===b.length},resetCache:function(){this._variables=this._rulesets=null;this._lookups={}},variables:function(){return this._variables?this._variables:this._variables=this.rules.reduce(function(b,g){g instanceof c.Rule&&!0===g.variable&&(b[g.name]=
g);return b},{})},variable:function(b){return this.variables()[b]},rulesets:function(){return this._rulesets?this._rulesets:this._rulesets=this.rules.filter(function(b){return b instanceof c.Ruleset||b instanceof c.mixin.Definition})},find:function(b,g){g=g||this;var e=[],f=b.toCSS();if(f in this._lookups)return this._lookups[f];this.rulesets().forEach(function(d){if(d!==g)for(var f=0;f<d.selectors.length;f++)if(b.match(d.selectors[f])){b.elements.length>d.selectors[f].elements.length?Array.prototype.push.apply(e,
d.find(new c.Selector(b.elements.slice(1)),g)):e.push(d);break}});return this._lookups[f]=e},toCSS:function(b,g){var e=[],f=[],d=[],h=[],n=[],k;this.root||this.joinSelectors(n,b,this.selectors);for(var l=0;l<this.rules.length;l++)if(k=this.rules[l],k.rules||k instanceof c.Media)h.push(k.toCSS(n,g));else if(k instanceof c.Directive){var q=k.toCSS(n,g);if("@charset"===k.name){if(g.charset){k.debugInfo&&(h.push(c.debugInfo(g,k)),h.push((new c.Comment("/* "+q.replace(/\n/g,"")+" */\n")).toCSS(g)));continue}g.charset=
!0}h.push(q)}else k instanceof c.Comment?k.silent||(this.root?h.push(k.toCSS(g)):f.push(k.toCSS(g))):k.toCSS&&!k.variable?f.push(k.toCSS(g)):k.value&&!k.variable&&f.push(k.value.toString());h=h.join("");if(this.root)e.push(f.join(g.compress?"":"\n"));else if(0<f.length){k=c.debugInfo(g,this);n=n.map(function(b){return b.map(function(b){return b.toCSS(g)}).join("").trim()}).join(g.compress?",":",\n");for(l=f.length-1;0<=l;l--)-1===d.indexOf(f[l])&&d.unshift(f[l]);e.push(k+n+(g.compress?"{":" {\n  ")+
d.join(g.compress?"":"\n  ")+(g.compress?"}":"\n}\n"))}e.push(h);return e.join("")+(g.compress?"\n":"")},joinSelectors:function(b,c,e){for(var f=0;f<e.length;f++)this.joinSelector(b,c,e[f])},joinSelector:function(b,g,e){var f,d,h,n,k,l,q,t,r,m,v,u;for(f=0;f<e.elements.length;f++)k=e.elements[f],"&"===k.value&&(n=!0);if(n){d=[];n=[[]];for(f=0;f<e.elements.length;f++)if(k=e.elements[f],"&"!==k.value)d.push(k);else{u=[];0<d.length&&this.mergeElementsOnToSelectors(d,n);for(d=0;d<n.length;d++)if(l=n[d],
0==g.length)0<l.length&&(l[0].elements=l[0].elements.slice(0),l[0].elements.push(new c.Element(k.combinator,"",0))),u.push(l);else for(h=0;h<g.length;h++)q=g[h],t=[],r=[],v=!0,0<l.length?(t=l.slice(0),m=t.pop(),m=new c.Selector(m.elements.slice(0)),v=!1):m=new c.Selector([]),1<q.length&&(r=r.concat(q.slice(1))),0<q.length&&(v=!1,m.elements.push(new c.Element(k.combinator,q[0].elements[0].value,0)),m.elements=m.elements.concat(q[0].elements.slice(1))),v||t.push(m),t=t.concat(r),u.push(t);n=u;d=[]}0<
d.length&&this.mergeElementsOnToSelectors(d,n);for(f=0;f<n.length;f++)b.push(n[f])}else if(0<g.length)for(f=0;f<g.length;f++)b.push(g[f].concat(e));else b.push([e])},mergeElementsOnToSelectors:function(b,g){var e,f;if(0==g.length)g.push([new c.Selector(b)]);else for(e=0;e<g.length;e++)f=g[e],0<f.length?f[f.length-1]=new c.Selector(f[f.length-1].elements.concat(b)):f.push(new c.Selector(b))}}})(q("../tree"));(function(c){c.Selector=function(b){this.elements=b};c.Selector.prototype.match=function(b){var c=
this.elements,e=c.length,f,d;b=b.elements.slice(b.elements.length&&"&"===b.elements[0].value?1:0);f=b.length;d=Math.min(e,f);if(0===f||e<f)return!1;for(e=0;e<d;e++)if(c[e].value!==b[e].value)return!1;return!0};c.Selector.prototype.eval=function(b){return new c.Selector(this.elements.map(function(c){return c.eval(b)}))};c.Selector.prototype.toCSS=function(b){if(this._css)return this._css;this._css=""===this.elements[0].combinator.value?" ":"";return this._css+=this.elements.map(function(c){return"string"===
typeof c?" "+c.trim():c.toCSS(b)}).join("")}})(q("../tree"));(function(c){c.UnicodeDescriptor=function(b){this.value=b};c.UnicodeDescriptor.prototype={toCSS:function(b){return this.value},eval:function(){return this}}})(q("../tree"));(function(c){c.URL=function(b,c){this.value=b;this.rootpath=c};c.URL.prototype={toCSS:function(){return"url("+this.value.toCSS()+")"},eval:function(b){b=this.value.eval(b);var g;"string"===typeof b.value&&!/^(?:[a-z-]+:|\/)/.test(b.value)&&(g=this.rootpath,b.quote||(g=
g.replace(/[\(\)'"\s]/g,function(b){return"\\"+b})),b.value=g+b.value);return new c.URL(b,this.rootpath)}}})(q("../tree"));(function(c){c.Value=function(b){this.value=b;this.is="value"};c.Value.prototype={eval:function(b){return 1===this.value.length?this.value[0].eval(b):new c.Value(this.value.map(function(c){return c.eval(b)}))},toCSS:function(b){return this.value.map(function(c){return c.toCSS(b)}).join(b.compress?",":", ")}}})(q("../tree"));(function(c){c.Variable=function(b,c,e){this.name=b;
this.index=c;this.file=e};c.Variable.prototype={eval:function(b){var g,e,f=this.name;0==f.indexOf("@@")&&(f="@"+(new c.Variable(f.slice(1))).eval(b).value);if(this.evaluating)throw{type:"Name",message:"Recursive variable definition for "+f,filename:this.file,index:this.index};this.evaluating=!0;if(g=c.find(b.frames,function(c){if(e=c.variable(f))return e.value.eval(b)}))return this.evaluating=!1,g;throw{type:"Name",message:"variable "+f+" is undefined",filename:this.file,index:this.index};}}})(q("../tree"));
(function(c){c.debugInfo=function(b,g){var e="";if(b.dumpLineNumbers&&!b.compress)switch(b.dumpLineNumbers){case "comments":e=c.debugInfo.asComment(g);break;case "mediaquery":e=c.debugInfo.asMediaQuery(g);break;case "all":e=c.debugInfo.asComment(g)+c.debugInfo.asMediaQuery(g)}return e};c.debugInfo.asComment=function(b){return"/* line "+b.debugInfo.lineNumber+", "+b.debugInfo.fileName+" */\n"};c.debugInfo.asMediaQuery=function(b){return"@media -sass-debug-info{filename{font-family:"+("file://"+b.debugInfo.fileName).replace(/[\/:.]/g,
"\\$&")+"}line{font-family:\\00003"+b.debugInfo.lineNumber+"}}\n"};c.find=function(b,c){for(var e=0,f;e<b.length;e++)if(f=c.call(b,b[e]))return f;return null};c.jsify=function(b){return Array.isArray(b.value)&&1<b.value.length?"["+b.value.map(function(b){return b.toCSS(!1)}).join(", ")+"]":b.toCSS(!1)}})(q("./tree"));var G=/^(file|chrome(-extension)?|resource|qrc|app):/.test(location.protocol);h.env=h.env||("127.0.0.1"==location.hostname||"0.0.0.0"==location.hostname||"localhost"==location.hostname||
0<location.port.length||G?"development":"production");h.async=h.async||!1;h.fileAsync=h.fileAsync||!1;h.poll=h.poll||(G?1E3:1500);if(h.functions)for(var A in h.functions)h.tree.functions[A]=h.functions[A];if(A=/!dumpLineNumbers:(comments|mediaquery|all)/.exec(location.hash))h.dumpLineNumbers=A[1];h.watch=function(){h.watchMode||(h.env="development",O());return this.watchMode=!0};h.unwatch=function(){clearInterval(h.watchTimer);return this.watchMode=!1};/!watch/.test(location.hash)&&h.watch();var t=
null;if("development"!=h.env)try{t="undefined"===typeof u.localStorage?null:u.localStorage}catch(T){}A=document.getElementsByTagName("link");var M=/^text\/(x-)?less$/;h.sheets=[];for(var C=0;C<A.length;C++)("stylesheet/less"===A[C].rel||A[C].rel.match(/stylesheet/)&&A[C].type.match(M))&&h.sheets.push(A[C]);var H="";h.modifyVars=function(c){var b=H;for(name in c)b+=("@"===name.slice(0,1)?"":"@")+name+": "+(";"===c[name].slice(-1)?c[name]:c[name]+";");(new h.Parser).parse(b,function(b,c){E(c.toCSS(),
h.sheets[h.sheets.length-1])})};h.refresh=function(c){var b,g;b=g=new Date;K(function(c,f,d,h,l){l.local?w("loading "+h.href+" from cache."):(w("parsed "+h.href+" successfully."),E(f.toCSS(),h,l.lastModified));w("css for "+h.href+" generated in "+(new Date-g)+"ms");0===l.remaining&&w("css generated in "+(new Date-b)+"ms");g=new Date},c);L()};h.refreshStyles=L;h.refresh("development"===h.env);"function"===typeof define&&define.amd&&define("less",[],function(){return h});_less=h})(window);
var less=_less,_salida="1";function procesar(u){a=less.Parser();a.parse(u,function(u,q){_salida=u?u.message:q.toCSS()});return _salida=_salida.replace(/alternate../g,"alternate")}function salida(){return"ss: "+_salida};
'''

import sys
import os
import io
import execjs

import re

BASE = os.path.dirname(__file__)

ctx = execjs.get()

lessc = ctx.compile(lesscss)

aless = lambda t: lessc.call('procesar', t)

def compilar_s(less_c):
	with open(less_c, 'r') as f_less:
		less = aless(f_less.read())
	return less

def compilar_mods(less_c):
	with open(less_c, 'r') as f_less:
		less = f_less.read()

	mods = re.findall(r'(.*)@import \'(.*)\'', less)

	less_cdir = os.path.dirname(less_c)

	for i, mod in mods:
		less_mod = os.path.join(less_cdir, mod)

		less_e = compilar_mods(less_mod + '.less')

		less_e = '\n'.join([ i + l for l in less_e.split('\n') ])

		less = less.replace(i + '@import \'%s\'' % mod, less_e)

	return less

compilar = lambda less_c: aless(compilar_mods(less_c))

if '__main__' == __name__:
	if 2 > len(sys.argv):
		print('lessc.py <fichero.ls>')
		sys.exit(0)

	print(compilar(sys.argv[1]))
